name: Testing Workflow

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  ##########################################################
  # Lint and Unit Test Jobs:
  # Install dependencies and execute lint debug then unit tests
  ##########################################################
  testing:
    name: 'Testing'
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.0.4'

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github.event.commits) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Checking local action
        id: commit-list
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        uses: ./.github/actions/commit-list
        with:
          github-context: ${{ toJSON(github) }}

      - name: Output commit list
        run: echo ${{ steps.commit-list.outputs.commit-list }} >> commit-list.txt

      - name: Archive Commit lList
        uses: actions/upload-artifact@v1
        with:
          name: Commit List
          path: commit-list.txt
